# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7.1.6
      - name: Install mise dependencies
        uses: jdx/mise-action@v3.3.1
        with:
          tool_versions: |
            ubi:railwayapp/railpack latest
      - name: Install dependencies
        run: |
          uv sync
      - name: Check & test
        env:
          DATABASE_URL_BASE: ""
          DATABASE_URL: ""
          RESEND_API_KEY: ""
          FERNET_KEY: ""
          SPRITES_TOKEN: ""
        run: |
          mise ci
